import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    appName: "MediBridge AI Rural Healthcare",
    dashboard: "Dashboard",
    scanner: "Prescription Scanner",
    lookup: "Medicine Directory",
    chat: "Health Chat",
    voice: "Elderly Voice Assistant",
    emergency: "Emergency Services",
    admin: "Admin Control",
    login: "Sign In",
    signup: "Register",
    logout: "Log Out",
    welcome: "Welcome",
    scanDescription: "Upload a picture of a doctor's prescription to understand it in simple language.",
    searchPlaceholder: "Search medicine by name or brand...",
    speakNow: "Tap mic and speak...",
    emergencyHelplines: "Emergency Contact Numbers",
    clinicsNearby: "Nearest Health Clinics",
    firstAid: "First-Aid Guidance",
    simplifiedInfo: "Simplified Information",
    medicineName: "Medicine Name",
    dosage: "Dosage (How much)",
    frequency: "Frequency (How often)",
    timing: "Timing (When to take)",
    duration: "Duration (How long)",
    instructions: "Instructions",
    sideEffects: "Common Side Effects",
    warnings: "Warnings / Precautions",
    generalAdvice: "General Health Advice",
    redFlags: "Emergency Stop Signs",
    downloadPDF: "Download PDF Report",
    readAloud: "Read Prescription Aloud",
    healthTip: "Health Tip of the Day",
    loading: "Processing, please wait...",
    error: "An error occurred",
    role: "User Role",
    history: "Recent Scans & History",
    noHistory: "No prescriptions scanned yet.",
    accessibility: "Accessibility Controls",
    highContrast: "High Contrast Mode",
    textSize: "Text Size",
    normal: "Normal",
    large: "Large",
    extraLarge: "Extra Large",
    patientName: "Patient Name",
    doctorName: "Doctor/Clinic",
    date: "Date",
    medicinesChecklist: "Medicines Checklist",
    whatItDoes: "What it does (Purpose)",
    scientificName: "Scientific Name",
    usedFor: "Used for",
    ttsContains: "This prescription contains",
    ttsMedicines: "medicines.",
    ttsMedicine: "Medicine",
    serverBusy: "The health translation assistant is currently busy due to high demand. Please try uploading again in a few moments.",
    rateLimit: "MediBridge AI is currently answering too many questions. Please wait a few seconds and send your message again."
  },
  hi: {
    appName: "आरोग्य ग्रामीण स्वास्थ्य",
    dashboard: "डैशबोर्ड",
    scanner: "पर्ची स्कैनर",
    lookup: "दवा निर्देशिका",
    chat: "स्वास्थ्य चैट",
    voice: "बुजुर्ग आवाज सहायक",
    emergency: "आपातकालीन सेवाएं",
    admin: "एडमिन कंट्रोल",
    login: "लॉगिन करें",
    signup: "पंजीकरण करें",
    logout: "लॉगआउट",
    welcome: "स्वागत है",
    scanDescription: "डॉक्टर की पर्ची को समझने के लिए उसकी फोटो अपलोड करें।",
    searchPlaceholder: "दवा का नाम लिखकर खोजें...",
    speakNow: "माइक दबाकर बोलें...",
    emergencyHelplines: "आपातकालीन हेल्पलाइन नंबर",
    clinicsNearby: "नजदीकी स्वास्थ्य केंद्र",
    firstAid: "प्राथमिक चिकित्सा निर्देश",
    simplifiedInfo: "सरलीकृत जानकारी",
    medicineName: "दवा का नाम",
    dosage: "खुराक (कितनी मात्रा)",
    frequency: "बारंबारता (दिन में कितनी बार)",
    timing: "समय (कब लेना है)",
    duration: "अवधि (कितने दिनों तक)",
    instructions: "विशेष निर्देश",
    sideEffects: "सामान्य दुष्प्रभाव",
    warnings: "सावधानियां और चेतावनियां",
    generalAdvice: "सामान्य स्वास्थ्य सलाह",
    redFlags: "खतरे के संकेत (तुरंत दवा रोकें)",
    downloadPDF: "पीडीएफ रिपोर्ट डाउनलोड करें",
    readAloud: "पर्ची बोलकर सुनें",
    healthTip: "आज की स्वास्थ्य सलाह",
    loading: "काम चल रहा है, कृपया प्रतीक्षा करें...",
    error: "एक त्रुटि हुई",
    role: "उपयोगकर्ता भूमिका",
    history: "हालिया स्कैन और इतिहास",
    noHistory: "अभी तक कोई पर्ची स्कैन नहीं की गई है।",
    accessibility: "सुलभता नियंत्रण (Accessibility)",
    highContrast: "उच्च कंट्रास्ट मोड",
    textSize: "अक्षर का आकार",
    normal: "सामान्य",
    large: "बड़ा",
    extraLarge: "बहुत बड़ा",
    patientName: "मरीज का नाम",
    doctorName: "डॉक्टर/क्लिनिक",
    date: "दिनांक",
    medicinesChecklist: "दवाओं की सूची",
    whatItDoes: "काम (उद्देश्य)",
    scientificName: "वैज्ञानिक नाम",
    usedFor: "इसके लिए उपयोगी है",
    ttsContains: "इस पर्ची में",
    ttsMedicines: "दवाएं हैं।",
    ttsMedicine: "दवा",
    serverBusy: "अनुवाद सहायक इस समय अत्यधिक कार्यभार के कारण व्यस्त है। कृपया कुछ ही क्षणों में फिर से प्रयास करें।",
    rateLimit: "आरोग्य इस समय कई सवालों के जवाब दे रहा है। कृपया कुछ सेकंड प्रतीक्षा करें और अपना संदेश पुनः भेजें।"
  },
  bn: {
    appName: "আরোগ্য গ্রামীণ স্বাস্থ্য",
    dashboard: "ড্যাশবোর্ড",
    scanner: "প্রেসক্রিপশন স্ক্যানার",
    lookup: "ওষুধের তালিকা",
    chat: "স্বাস্থ্য চ্যাট",
    voice: "বয়স্ক ভয়েস অ্যাসিস্ট্যান্ট",
    emergency: "জরুরি সেবা",
    admin: "অ্যাডমিন কন্ট্রোল",
    login: "লগইন",
    signup: "রেজিস্ট্রেশন",
    welcome: "স্বাগতম",
    scanDescription: "সহজ ভাষায় বোঝার জন্য প্রেসক্রিপশনের ছবি আপলোড করুন।",
    searchPlaceholder: "ওষুধের নাম খুঁজুন...",
    speakNow: "মাইক টিপে কথা বলুন...",
    emergencyHelplines: "জরুরি নম্বর",
    clinicsNearby: "নিকটবর্তী ক্লিনিক",
    firstAid: "প্রাথমিক চিকিৎসা নির্দেশিকা",
    simplifiedInfo: "সহজ তথ্য",
    medicineName: "ওষুধের নাম",
    dosage: "মাত্রা (কতটুকু)",
    frequency: "কতবার",
    timing: "কখন নেবেন",
    duration: "কতদিন নেবেন",
    instructions: "বিশেষ নির্দেশাবলী",
    sideEffects: "পার্শ্বপ্রতিক্রিয়া",
    warnings: "সতর্কতা",
    generalAdvice: "সাধারণ পরামর্শ",
    redFlags: "জরুরি সতর্কতা সংকেত",
    downloadPDF: "পিডিএফ ডাউনলোড করুন",
    readAloud: "প্রেসক্রিপশন শুনুন",
    healthTip: "আজকের স্বাস্থ্য টিপস",
    loading: "প্রক্রিয়াকরণ চলছে...",
    error: "ত্রুটি ঘটেছে",
    role: "ভূমিকা",
    history: "সাম্প্রতিক ইতিহাস",
    noHistory: "কোনো প্রেসক্রিপশন স্ক্যান করা হয়নি।",
    accessibility: "অ্যাক্সেসিবিলিটি নিয়ন্ত্রণ",
    highContrast: "হাই কনট্রাস্ট মোড",
    textSize: "অক্ষরের আকার",
    normal: "স্বাভাবিক",
    large: "বড়",
    extraLarge: "খুব বড়",
    patientName: "রোগীর নাম",
    doctorName: "ডাক্তার/ক্লিনিক",
    date: "তারিখ",
    medicinesChecklist: "ওষুধের তালিকা",
    whatItDoes: "কাজ (উদ্দেশ্য)",
    scientificName: "বৈজ্ঞানিক নাম",
    usedFor: "এর জন্য ব্যবহার করা হয়",
    ttsContains: "এই প্রেসক্রিপশনে",
    ttsMedicines: "টি ওষুধ আছে।",
    ttsMedicine: "ওষুধ",
    serverBusy: "অনুবাদ সহকারী বর্তমানে ব্যস্ত রয়েছে। অনুগ্রহ করে একটু পরে আবার চেষ্টা করুন।",
    rateLimit: "আরোগ্য বর্তমানে অনেক প্রশ্নের উত্তর দিচ্ছে। অনুগ্রহ করে কয়েক সেকেন্ড অপেক্ষা করে আবার বার্তা পাঠান।"
  },
  mr: {
    appName: "आरोग्य ग्रामीण आरोग्य",
    dashboard: "डॅशबोर्ड",
    scanner: "प्रिस्क्रिप्शन स्कॅनर",
    lookup: "औषध निर्देशिका",
    chat: "आरोग्य चॅट",
    voice: "वृद्ध आवाज सहाय्यक",
    emergency: "अत्यावश्यक सेवा",
    admin: "अॅडमिन कंट्रोल",
    login: "लॉगिन करा",
    signup: "नोंदणी करा",
    welcome: "स्वागत आहे",
    scanDescription: "डॉक्टरांचे प्रिस्क्रिप्शन सोप्या भाषेत समजून घेण्यासाठी त्याचा फोटो अपलोड करा.",
    searchPlaceholder: "औषधाचे नाव शोधा...",
    speakNow: "माईक दाबून बोला...",
    emergencyHelplines: "अत्यावश्यक क्रमांक",
    clinicsNearby: "जवळचे आरोग्य केंद्र",
    firstAid: "प्रथमोपचार मार्गदर्शिका",
    simplifiedInfo: "सोपी माहिती",
    medicineName: "औषधाचे नाव",
    dosage: "खुराक (किती घ्यायचे)",
    frequency: "वारंवारता (किती वेळा)",
    timing: "वेळ (कधी घ्यायचे)",
    duration: "कालावधी (किती दिवस)",
    instructions: "विशेष सूचना",
    sideEffects: "दुष्परिणाम",
    warnings: "सावधानता आणि चेतावणी",
    generalAdvice: "सामान्य आरोग्य सल्ला",
    redFlags: "धोक्याचे संकेत",
    downloadPDF: "पीडीएफ डाउनलोड करा",
    readAloud: "प्रिस्क्रिप्शन वाचून ऐका",
    healthTip: "आजची आरोग्य टीप",
    loading: "प्रक्रिया सुरू आहे...",
    error: "त्रुटी आली",
    role: "भूमिका",
    history: "इतिहास",
    noHistory: "अद्याप एकही स्कॅन केलेले नाही.",
    accessibility: "अॅक्सेसिबिलिटी नियंत्रणे",
    highContrast: "हाय कॉन्ट्रास्ट मोड",
    textSize: "मजकुराचा आकार",
    normal: "सामान्य",
    large: "मोठा",
    extraLarge: "खूप मोठा",
    patientName: "रुग्णाचे नाव",
    doctorName: "डॉक्टर/क्लिनिक",
    date: "तारीख",
    medicinesChecklist: "औषधांची यादी",
    whatItDoes: "काम (उद्देश्य)",
    scientificName: "वैज्ञानिक नाव",
    usedFor: "यासाठी वापरले जाते",
    ttsContains: "या प्रिस्क्रिप्शनमध्ये",
    ttsMedicines: "औषधे आहेत.",
    ttsMedicine: "औषध",
    serverBusy: "अनुवाद सहाय्यक सध्या व्यस्त आहे. कृपया काही वेळाने पुन्हा प्रयत्न करा।",
    rateLimit: "आरोग्य सध्या अनेक प्रश्नांची उत्तरे देत आहे. कृपया काही सेकंद थांबा आणि तुमचा संदेश पुन्हा पाठवा।"
  },
  te: {
    appName: "ఆరోగ్య గ్రామీణ వైద్యం",
    dashboard: "డాష్‌బోర్డ్",
    scanner: "ప్రిస్క్రిప్షన్ స్కానర్",
    lookup: "మందుల డైరెక్టరీ",
    chat: "హెల్త్ చాట్",
    voice: "వృద్ధుల వాయిస్ అసిస్టెంట్",
    emergency: "అత్యవసర సేవలు",
    admin: "అడ్మిన్ నియంత్రణ",
    login: "లాగిన్",
    signup: "నమోదు చేసుకోండి",
    welcome: "స్వాగతం",
    scanDescription: "వైద్యుడి ప్రిస్క్రిప్షన్‌ను సులభమైన భాషలో అర్థం చేసుకోవడానికి ఫోటోను అప్‌లోడ్ చేయండి.",
    searchPlaceholder: "మందు పేరుతో శోధించండి...",
    speakNow: "మైక్ నొక్కి మాట్లాడండి...",
    emergencyHelplines: "అత్యవసర హెల్ప్‌లైన్ నంబర్లు",
    clinicsNearby: "దగ్గరి ఆరోగ్య కేంద్రాలు",
    firstAid: "ప్రథమ చికిత్స మార్గదర్శకాలు",
    simplifiedInfo: "సులभ సమాచారం",
    medicineName: "మందు పేరు",
    dosage: "డోస్ (ఎంత తీసుకోవాలి)",
    frequency: "ఫ్రీక్వెన్సీ (ఎన్ని సార్లు)",
    timing: "సమయం (ఎప్పుడు తీసుకోవాలి)",
    duration: "వ్యవధి (ఎన్ని రోజులు)",
    instructions: "ప్రత్యేక సూచనలు",
    sideEffects: "దుష్ప్రభావాలు",
    warnings: "హెచ్చరికలు మరియు జాగ్రత్తలు",
    generalAdvice: "సాధారణ ఆరోగ్య సలహా",
    redFlags: "ప్రమాద సంకేతాలు",
    downloadPDF: "పీడీఎఫ్ రిపోర్ట్ డౌన్‌లోడ్ చేసుకోండి",
    readAloud: "ప్రిస్క్రిప్షన్ చదివి వినిపించు",
    healthTip: "నేటి ఆరోగ్య చిట్కా",
    loading: "ప్రాసెస్ అవుతోంది...",
    error: "ఒక లోపం సంభవించింది",
    role: "పాత్ర",
    history: "గత చరిత్ర",
    noHistory: "ఇంకా ఎలాంటి ప్రిస్క్రిప్షన్ స్క్యాన్ చేయలేదు.",
    accessibility: "యాక్సెస్బిలిటీ నియంత్రణలు",
    highContrast: "హై కాంట్రాస్ట్ మోడ్",
    textSize: "అక్షర పరిమాణం",
    normal: "సాధారణ",
    large: "పెద్దది",
    extraLarge: "చాలా పెద్దది",
    patientName: "రోగి పేరు",
    doctorName: "వైద్యుడు/క్లినిక్",
    date: "తేదీ",
    medicinesChecklist: "మందుల జాబితా",
    whatItDoes: "పని (ఉద్దేశ్యం)",
    scientificName: "శాస్త్రీయ నామం",
    usedFor: "దీని కోసం ఉపయోగించబడుతుంది",
    ttsContains: "ఈ ప్రిస్క్రిప్షన్ లో",
    ttsMedicines: "మందులు ఉన్నాయి.",
    ttsMedicine: "మందు",
    serverBusy: "అనువాద సహాయకుడు ప్రస్తుతం బిజీగా ఉన్నాడు. దయచేసి కాసేపటి తర్వాత మళ్ళీ ప్రయత్నించండి.",
    rateLimit: "ఆరోగ్య ప్రస్తుతం చాలా ప్రశ్నలకు సమాధానాలు ఇస్తోంది. దయచేసి కొన్ని సెకన్లు వేచి ఉండి, మీ సందేశాన్ని మళ్లీ పంపండి."
  },
  ta: {
    appName: "ஆரோக்யா கிராமப்புற சுகாதாரம்",
    dashboard: "டாஷ்போர்டு",
    scanner: "பிரிஸ்கிரிப்ஷன் ஸ்கேனர்",
    lookup: "மருந்து விவரகம்",
    chat: "சுகாதார அரட்டை",
    voice: "முதியோருக்கான குரல் உதவியாளர்",
    emergency: "அவசரகால சேவைகள்",
    admin: "நிர்வாகக் கட்டுப்பாடு",
    login: "உள்நுழை",
    signup: "பதிவு செய்க",
    welcome: "வரவேற்கிறோம்",
    scanDescription: "மருத்துவரின் சீட்டை எளிய மொழியில் புரிந்து கொள்ள அதன் புகைப்படத்தை பதிவேற்றவும்.",
    searchPlaceholder: "மருந்தின் பெயரைத் தேடவும்...",
    speakNow: "மைக்கை அழுத்திப் பேசவும்...",
    emergencyHelplines: "அவசரகால எண்கள்",
    clinicsNearby: "அருகிலுள்ள மருத்துவமனைகள்",
    firstAid: "முதலுதவி வழிகாட்டுதல்கள்",
    simplifiedInfo: "எளிமைப்படுத்தப்பட்ட தகவல்",
    medicineName: "மருந்தின் பெயர்",
    dosage: "அளவு",
    frequency: "எத்தனை முறை",
    timing: "நேரம் (எப்போது உட்கொள்ள வேண்டும்)",
    duration: "கால அளவு (எத்தனை நாட்கள்)",
    instructions: "சிறப்பு வழிமுறைகள்",
    sideEffects: "பக்க விளைவுகள்",
    warnings: "எச்சரிக்கைகள் / முன்னெச்சரிக்கைகள்",
    generalAdvice: "பொதுவான சுகாதார ஆலோசனை",
    redFlags: "அபாய அறிகுறிகள்",
    downloadPDF: "பிடிஎஃப் அறிக்கையைப் பதிவிறக்குக",
    readAloud: "சீட்டை உரக்க வாசி",
    healthTip: "இன்றைய சுகாதார குறிப்பு",
    loading: "செயலாக்கப்படும், காத்திருக்கவும்...",
    error: "ஒரு பிழை ஏற்பட்டது",
    role: "பயனர் பங்கு",
    history: "சமீபத்திய வரலாறு",
    noHistory: "பிரிஸ்கிரிப்ஷன் இன்னும் ஸ்கேன் செய்யப்படவில்லை.",
    accessibility: "அணுகல்தன்மை கட்டுப்பாடுகள்",
    highContrast: "உயர் கான்ட்ராஸ்ட் முறை",
    textSize: "எழுத்து அளவு",
    normal: "சாதாரண",
    large: "பெரிய",
    extraLarge: "மிகப் பெரியது",
    patientName: "நோயாளி பெயர்",
    doctorName: "மருத்துவர்/மருத்துவமனை",
    date: "தேதி",
    medicinesChecklist: "மருந்துகள் பட்டியல்",
    whatItDoes: "செயல்பாடு (நோக்கம்)",
    scientificName: "அறிவியல் பெயர்",
    usedFor: "இதற்குப் பயன்படுத்தப்படுகிறது",
    ttsContains: "இந்த சீட்டில்",
    ttsMedicines: "மருந்துகள் உள்ளன.",
    ttsMedicine: "மருந்து",
    serverBusy: "மொழிபெயர்ப்பு உதவியாளர் தற்போது பிஸியாக உள்ளார். தயவுசெய்து சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.",
    rateLimit: "ஆரோக்யா தற்போது பல கேள்விகளுக்கு பதிலளித்து வருகிறது. தயவுசெய்து சில நொடிகள் காத்திருந்து உங்கள் செய்தியை மீண்டும் அனுப்பவும்."
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('languagePreference') || 'en';
  });

  const setLanguage = (lang) => {
    setLanguageState(lang);
    localStorage.setItem('languagePreference', lang);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  const languages = [
    { code: 'en', label: 'English' },
    { code: 'hi', label: 'हिन्दी (Hindi)' },
    { code: 'bn', label: 'বাংলা (Bengali)' },
    { code: 'mr', label: 'मराठी (Marathi)' },
    { code: 'te', label: 'తెలుగు (Telugu)' },
    { code: 'ta', label: 'தமிழ் (Tamil)' }
  ];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
