import React, { useState, useEffect, useRef } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { api } from '../utils/api';
import { useLanguage } from '../context/LanguageContext';
import { useAccessibility } from '../context/AccessibilityContext';
import {
  Upload,
  FileImage,
  Volume2,
  Download,
  Trash2,
  FileText,
  AlertTriangle,
  Info,
  Calendar,
  User,
  Heart,
  ChevronLeft
} from 'lucide-react';

const PrescriptionScanner = () => {
  const { t, language } = useLanguage();
  const { speakText, stopSpeaking, isSpeaking } = useAccessibility();
  
  const location = useLocation();
  const navigate = useNavigate();
  const fileInputRef = useRef(null);

  const [file, setFile] = useState(null);
  const [previewUrl, setPreviewUrl] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [activePrescription, setActivePrescription] = useState(null);
  const [selectedLanguage, setSelectedLanguage] = useState(language);

  // Sync selected language with global language selection
  useEffect(() => {
    setSelectedLanguage(language);
  }, [language]);

  // Load prescription by ID if specified in URL query
  useEffect(() => {
    const params = new URLSearchParams(location.search);
    const id = params.get('id');
    if (id) {
      loadPrescription(id, language);
    } else {
      setActivePrescription(null);
      setPreviewUrl(null);
      setFile(null);
    }
  }, [location.search, language]);

  const loadPrescription = async (id, lang = language) => {
    setLoading(true);
    setError('');
    try {
      const res = await api.getPrescriptionById(id, lang);
      if (res.success) {
        setActivePrescription(res.data);
        setPreviewUrl(res.data.imagePath);
      } else {
        const errorMsg = res.message === 'SERVER_BUSY' ? t('serverBusy') : (res.message || 'Failed to load prescription');
        setError(errorMsg);
        speakText(errorMsg);
      }
    } catch (err) {
      setError('Error connecting to backend.');
    } finally {
      setLoading(false);
    }
  };

  const handleFileChange = (e) => {
    const selected = e.target.files[0];
    if (!selected) return;

    if (!selected.type.startsWith('image/') && selected.type !== 'application/pdf') {
      setError('Please upload an image (PNG, JPEG) or a PDF file.');
      return;
    }

    setFile(selected);
    setError('');

    // Create a local object URL for preview
    const reader = new FileReader();
    reader.onloadend = () => {
      setPreviewUrl(reader.result);
    };
    reader.readAsDataURL(selected);
  };

  const handleUploadSubmit = async (e) => {
    e.preventDefault();
    if (!file) return;

    setLoading(true);
    setError('');
    setActivePrescription(null);

    const formData = new FormData();
    formData.append('file', file);
    formData.append('language', selectedLanguage);

    try {
      const res = await api.uploadPrescription(formData);
      if (res.success) {
        setActivePrescription(res.data);
        // Clean up inputs
        setFile(null);
        navigate(`/ocr?id=${res.data._id}`);
      } else {
        const errorMsg = res.message === 'SERVER_BUSY' ? t('serverBusy') : (res.message || 'Prescription OCR parsing failed. Please try a clearer picture.');
        setError(errorMsg);
        speakText(errorMsg);
      }
    } catch (err) {
      console.error(err);
      setError('Server error during processing. Please verify network.');
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async () => {
    if (!activePrescription) return;
    if (window.confirm('Are you sure you want to delete this prescription?')) {
      try {
        const res = await api.deletePrescription(activePrescription._id);
        if (res.success) {
          navigate('/ocr');
        }
      } catch (err) {
        setError('Failed to delete prescription.');
      }
    }
  };

  /**
   * Narrates the entire prescription in simple language
   */
  const readFullPrescription = () => {
    if (!activePrescription) return;
    const content = activePrescription.simplifiedContent;
    const currentLang = activePrescription.language || language;
    
    // Construct local-fallback regional script if not generated by Gemini
    let localNarr = `${t('patientName')}: ${content.patientName || 'Unknown'}. `;
    if (content.doctorName) localNarr += `${t('doctorName')}: ${content.doctorName}. `;
    
    localNarr += `${t('ttsContains')} ${content.medicines.length} ${t('ttsMedicines')} `;
    
    content.medicines.forEach((med, idx) => {
      localNarr += `${t('ttsMedicine')} ${idx + 1}: ${med.name}. `;
      if (med.genericName) localNarr += `${t('scientificName')}: ${med.genericName}. `;
      localNarr += `${t('usedFor')}: ${med.purposeSimple}. `;
      localNarr += `${t('dosage')}: ${med.dosage}. ${t('frequency')}: ${med.frequency}. ${t('timing')}: ${med.timing}. ${t('duration')}: ${med.duration}. `;
      if (med.instructions) localNarr += `${t('instructions')}: ${med.instructions}. `;
    });

    if (content.generalAdvice) {
      localNarr += `${t('generalAdvice')}: ${content.generalAdvice}. `;
    }

    if (content.emergencyInstructions) {
      localNarr += `${t('redFlags')}: ${content.emergencyInstructions}`;
    }

    // Pass the pre-rendered Devanagari text (ttsNarration) or constructed local script,
    // and the transliterated English-script fallback text (ttsTransliterated)
    speakText(
      content.ttsNarration || localNarr,
      currentLang,
      content.ttsTransliterated || localNarr
    );
  };

  /**
   * Reads a single medicine details aloud
   */
  const readSingleMedicine = (med) => {
    let narr = `${med.name}. `;
    if (med.genericName) narr += `${t('scientificName')}: ${med.genericName}. `;
    narr += `${t('usedFor')}: ${med.purposeSimple}. `;
    narr += `${t('dosage')}: ${med.dosage}. ${t('frequency')}: ${med.frequency}. ${t('timing')}: ${med.timing}. ${t('duration')}: ${med.duration}. `;
    if (med.instructions) narr += `${t('instructions')}: ${med.instructions}. `;
    
    // For single medicine, we pass it as both text and fallback since brand names are already English
    speakText(narr, activePrescription.language || language, narr);
  };

  return (
    <div className="space-y-6">
      
      {/* Back button when viewing active details */}
      {activePrescription && (
        <button
          onClick={() => navigate('/ocr')}
          className="flex items-center gap-1.5 px-3 py-1.5 bg-gray-100 dark:bg-navy-800 hover:bg-gray-200 dark:hover:bg-navy-700 text-gray-700 dark:text-navy-200 rounded-xl text-sm font-semibold transition-all focus:outline-none"
        >
          <ChevronLeft className="w-4 h-4" />
          <span>Upload Another</span>
        </button>
      )}

      {error && (
        <div className="p-4 rounded-2xl bg-red-50 dark:bg-red-950/30 border border-red-100 dark:border-red-900/50 text-red-700 dark:text-red-300 text-sm flex items-start gap-2.5">
          <AlertTriangle className="w-5 h-5 flex-shrink-0" />
          <p className="font-semibold leading-relaxed">{error}</p>
        </div>
      )}

      {!activePrescription ? (
        /* Scanned File Uploader Frame */
        <div className="max-w-2xl mx-auto bg-white dark:bg-navy-900 border border-gray-100 dark:border-navy-800 rounded-3xl p-6 sm:p-8 shadow-sm">
          <h2 className="font-bold text-xl sm:text-2xl text-gray-800 dark:text-white text-center">
            {t('scanner')}
          </h2>
          <p className="text-center text-sm text-gray-500 dark:text-navy-400 mt-1.5 leading-relaxed">
            {t('scanDescription')}
          </p>

          <form onSubmit={handleUploadSubmit} className="mt-8 space-y-6">
            
            {/* File Drag Area */}
            <div
              onClick={() => fileInputRef.current.click()}
              className={`border-2 border-dashed rounded-2xl p-8 flex flex-col items-center justify-center cursor-pointer transition-all hover:bg-gray-50 dark:hover:bg-navy-800/40 ${
                file ? 'border-healthcare-500 bg-healthcare-50/20' : 'border-gray-300 dark:border-navy-700'
              }`}
            >
              <input
                type="file"
                ref={fileInputRef}
                onChange={handleFileChange}
                accept="image/*,application/pdf"
                className="hidden"
              />
              <Upload className={`w-12 h-12 mb-3 ${file ? 'text-healthcare-500' : 'text-gray-400'}`} />
              <p className="font-bold text-sm sm:text-base text-gray-700 dark:text-navy-205">
                {file ? file.name : 'Select Prescription Image or PDF'}
              </p>
              <p className="text-xs text-gray-400 dark:text-navy-400 mt-1">
                Supports PNG, JPEG, PDF up to 10MB
              </p>
            </div>

            {/* Language targeting selectors */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 bg-gray-50 dark:bg-navy-800 rounded-2xl border border-gray-100 dark:border-navy-700">
              <div>
                <label className="block text-sm font-semibold text-gray-700 dark:text-navy-300">
                  Target Simplification Language
                </label>
                <p className="text-xs text-gray-405 mt-0.5">
                  The prescription will be explained and translated into this language.
                </p>
              </div>
              <select
                value={selectedLanguage}
                onChange={(e) => setSelectedLanguage(e.target.value)}
                className="px-3 py-2 bg-white dark:bg-navy-900 border border-gray-205 dark:border-navy-700 rounded-xl text-sm focus:outline-none text-gray-800 dark:text-white"
              >
                <option value="en">English (अंग्रेजी)</option>
                <option value="hi">हिन्दी (Hindi)</option>
                <option value="bn">বাংলা (Bengali)</option>
                <option value="mr">मराठी (Marathi)</option>
                <option value="te">తెలుగు (Telugu)</option>
                <option value="ta">தமிழ் (Tamil)</option>
              </select>
            </div>

            {/* Submission triggers */}
            {file && (
              <button
                type="submit"
                disabled={loading}
                className="w-full py-3.5 bg-healthcare-500 hover:bg-healthcare-600 disabled:bg-healthcare-300 text-white font-bold rounded-2xl shadow-md transition-all focus:outline-none"
              >
                {loading ? t('loading') : 'Start Simplifying Scan'}
              </button>
            )}
          </form>

          {/* Loader indicator */}
          {loading && (
            <div className="mt-8 flex flex-col items-center justify-center space-y-3">
              <div className="w-10 h-10 border-4 border-healthcare-200 border-t-healthcare-600 rounded-full animate-spin" />
              <p className="text-sm font-semibold text-gray-600 dark:text-navy-300 animate-pulse">
                Analyzing prescription & medicines. Translating details...
              </p>
            </div>
          )}
        </div>
      ) : (
        /* Simplified Split Screen Dashboard */
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
          
          {/* Left Panel: Original Scan Preview */}
          <div className="lg:col-span-5 bg-white dark:bg-navy-900 border border-gray-100 dark:border-navy-800 rounded-3xl p-4 shadow-sm">
            <h3 className="font-bold text-base text-gray-805 dark:text-white mb-3 flex items-center gap-1.5">
              <FileImage className="w-5 h-5 text-healthcare-500" />
              <span>Original Prescription Image</span>
            </h3>
            <div className="rounded-2xl border border-gray-100 dark:border-navy-800 overflow-hidden bg-gray-50 dark:bg-navy-950 flex items-center justify-center max-h-[500px]">
              {previewUrl ? (
                previewUrl.startsWith('data:application/pdf;') ? (
                  <div className="p-10 text-center text-sm text-gray-400">
                    <FileText className="w-16 h-16 mx-auto mb-3 text-red-500" />
                    <span>PDF Prescription Document Scanned</span>
                  </div>
                ) : (
                  <img
                    src={previewUrl}
                    alt="Prescription preview"
                    className="max-w-full max-h-full object-contain hover:scale-105 transition-transform duration-300"
                  />
                )
              ) : (
                <div className="p-10 text-center text-sm text-gray-400">No preview available</div>
              )}
            </div>
          </div>

          {/* Right Panel: Simplified AI Output */}
          <div className="lg:col-span-7 space-y-5">
            
            {/* Header Metrics Card */}
            <div className="bg-white dark:bg-navy-900 border border-gray-100 dark:border-navy-800 rounded-3xl p-5 shadow-sm space-y-4">
              <div className="flex flex-wrap items-center justify-between gap-3 border-b border-gray-100 dark:border-navy-850 pb-4">
                <div>
                  <span className="text-xs font-semibold text-gray-400 uppercase tracking-wider">
                    Scan Simplified Summary
                  </span>
                  <h3 className="font-bold text-xl text-gray-805 dark:text-white mt-0.5">
                    {t('simplifiedInfo')}
                  </h3>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={readFullPrescription}
                    className={`flex items-center gap-1.5 px-3.5 py-1.8 bg-healthcare-500 hover:bg-healthcare-600 text-white rounded-xl text-xs sm:text-sm font-bold shadow-md transition-all focus:outline-none ${
                      isSpeaking ? 'ring-4 ring-healthcare-200 dark:ring-healthcare-950' : ''
                    }`}
                    title={t('readAloud')}
                  >
                    <Volume2 className="w-4 h-4" />
                    <span>{t('readAloud')}</span>
                  </button>
                  <a
                    href={api.downloadPDFUrl(activePrescription._id)}
                    download={`simplified_prescription_${activePrescription._id}.pdf`}
                    className="flex items-center gap-1.5 px-3.5 py-1.8 bg-blue-500 hover:bg-blue-600 text-white rounded-xl text-xs sm:text-sm font-bold shadow-md transition-all"
                  >
                    <Download className="w-4 h-4" />
                    <span className="hidden sm:inline">PDF</span>
                  </a>
                  <button
                    onClick={handleDelete}
                    className="p-2 text-red-500 hover:bg-red-50 dark:hover:bg-red-950 rounded-xl transition-all"
                    title="Delete Scan Record"
                  >
                    <Trash2 className="w-4.5 h-4.5" />
                  </button>
                </div>
              </div>

              {/* Metadata columns */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm">
                <div className="flex items-center gap-2 text-gray-650 dark:text-navy-300">
                  <User className="w-4 h-4 text-healthcare-600 dark:text-healthcare-400" />
                  <span><strong>{t('patientName')}:</strong> {activePrescription.simplifiedContent.patientName || 'Unknown'}</span>
                </div>
                <div className="flex items-center gap-2 text-gray-650 dark:text-navy-300">
                  <Calendar className="w-4 h-4 text-healthcare-600 dark:text-healthcare-405" />
                  <span><strong>{t('date')}:</strong> {activePrescription.simplifiedContent.date || 'Unknown'}</span>
                </div>
                <div className="flex items-center gap-2 text-gray-650 dark:text-navy-300 sm:col-span-2">
                  <Info className="w-4 h-4 text-healthcare-605 dark:text-healthcare-400" />
                  <span><strong>{t('doctorName')}:</strong> {activePrescription.simplifiedContent.doctorName || 'Unknown'}</span>
                </div>
              </div>
            </div>

            {/* Medicines List Section */}
            <div className="space-y-4">
              <h4 className="font-bold text-lg text-gray-800 dark:text-white flex items-center gap-2">
                <Heart className="w-5 h-5 text-healthcare-500" />
                <span>{t('medicinesChecklist')}</span>
              </h4>

              {activePrescription.simplifiedContent.medicines?.map((med, index) => (
                <div
                  key={index}
                  className="bg-white dark:bg-navy-900 border border-gray-100 dark:border-navy-800 hover:border-healthcare-300 dark:hover:border-healthcare-800 rounded-2xl p-5 shadow-sm transition-all"
                >
                  <div className="flex items-start justify-between gap-3 border-b border-gray-50 dark:border-navy-850 pb-3 mb-3">
                    <div>
                      {/* Name in bold English (matching packaging) */}
                      <h5 className="font-bold text-lg text-healthcare-700 dark:text-healthcare-400">
                        {med.name}
                      </h5>
                      <p className="text-xs text-gray-400 dark:text-navy-450 italic mt-0.5">
                        Scientific Name: {med.genericName || 'Not identified'}
                      </p>
                    </div>
                    <button
                      onClick={() => readSingleMedicine(med)}
                      className="p-1.5 bg-gray-50 dark:bg-navy-800 text-healthcare-600 dark:text-healthcare-400 hover:bg-healthcare-50 dark:hover:bg-navy-700 rounded-lg transition-all"
                      title="Listen to details"
                    >
                      <Volume2 className="w-4 h-4" />
                    </button>
                  </div>

                  {/* Medicine Details Grid */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm">
                    <div className="p-2 bg-gray-50 dark:bg-navy-800/40 rounded-xl">
                      <span className="block text-xs font-semibold text-gray-400 uppercase">
                        {t('dosage')}
                      </span>
                      <span className="font-bold text-gray-700 dark:text-navy-200">{med.dosage || '-'}</span>
                    </div>

                    <div className="p-2 bg-gray-50 dark:bg-navy-800/40 rounded-xl">
                      <span className="block text-xs font-semibold text-gray-400 uppercase">
                        {t('frequency')}
                      </span>
                      <span className="font-bold text-gray-700 dark:text-navy-200">{med.frequency || '-'}</span>
                    </div>

                    <div className="p-2 bg-gray-50 dark:bg-navy-800/40 rounded-xl">
                      <span className="block text-xs font-semibold text-gray-405 uppercase">
                        {t('timing')}
                      </span>
                      <span className="font-bold text-healthcare-600 dark:text-healthcare-400">{med.timing || '-'}</span>
                    </div>

                    <div className="p-2 bg-gray-50 dark:bg-navy-800/40 rounded-xl">
                      <span className="block text-xs font-semibold text-gray-400 uppercase">
                        {t('duration')}
                      </span>
                      <span className="font-bold text-gray-700 dark:text-navy-200">{med.duration || '-'}</span>
                    </div>

                    <div className="sm:col-span-2 p-2 bg-teal-50/20 dark:bg-teal-950/10 rounded-xl border border-teal-50 dark:border-teal-950/40">
                      <span className="block text-xs font-semibold text-teal-650 dark:text-teal-400 uppercase">
                        {t('whatItDoes')}
                      </span>
                      <span className="text-teal-800 dark:text-teal-300 leading-relaxed font-semibold">
                        {med.purposeSimple || '-'}
                      </span>
                    </div>

                    {med.instructions && (
                      <div className="sm:col-span-2 p-2 bg-amber-50/20 dark:bg-amber-950/10 rounded-xl border border-amber-50 dark:border-amber-950/40">
                        <span className="block text-xs font-semibold text-amber-600 dark:text-amber-450 uppercase">
                          {t('instructions')}
                        </span>
                        <span className="text-amber-800 dark:text-amber-300 font-semibold leading-relaxed">
                          {med.instructions}
                        </span>
                      </div>
                    )}

                    {med.sideEffects && med.sideEffects.length > 0 && (
                      <div className="sm:col-span-2 p-2 bg-gray-50 dark:bg-navy-800/20 rounded-xl">
                        <span className="block text-xs font-semibold text-gray-400 uppercase">
                          {t('sideEffects')}
                        </span>
                        <span className="text-gray-655 dark:text-navy-300">
                          {med.sideEffects.join(', ')}
                        </span>
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>

            {/* General Advice box */}
            {activePrescription.simplifiedContent.generalAdvice && (
              <div className="p-5 bg-gradient-to-br from-healthcare-50/40 to-teal-50/30 dark:from-healthcare-950/20 dark:to-teal-950/10 border border-healthcare-100 dark:border-healthcare-900 rounded-3xl shadow-sm">
                <h4 className="font-bold text-base text-healthcare-805 dark:text-healthcare-300 mb-2 flex items-center gap-1.5">
                  <Info className="w-5 h-5 text-healthcare-500" />
                  <span>{t('generalAdvice')}</span>
                </h4>
                <p className="text-sm text-healthcare-700 dark:text-healthcare-200 leading-relaxed font-semibold">
                  {activePrescription.simplifiedContent.generalAdvice}
                </p>
              </div>
            )}

            {/* Emergency Warnings */}
            {activePrescription.simplifiedContent.emergencyInstructions && (
              <div className="p-5 bg-red-50 dark:bg-red-950/20 border border-red-100 dark:border-red-900/50 rounded-3xl shadow-sm">
                <h4 className="font-bold text-base text-red-800 dark:text-red-405 mb-2 flex items-center gap-1.5">
                  <AlertTriangle className="w-5 h-5 text-red-500 animate-pulse" />
                  <span>{t('redFlags')}</span>
                </h4>
                <p className="text-sm text-red-700 dark:text-red-300 leading-relaxed font-semibold">
                  {activePrescription.simplifiedContent.emergencyInstructions}
                </p>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default PrescriptionScanner;
